[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
  functions = "functions" # Path to serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
